### ISSUE TITLE
Genie VM Prototype 생성

### ISSUE THREAD

**Issue by dhslove** [ablecloud-team/ablestack-genie#1]
VM 방식으로 Genie를 서비스 하기 위해 Genie VM에 대한 Prototype 제작

- [ ] 싱글 VM 아키텍처, CentOS 8.5 사용
- [ ] Docker 기반 MiniKube 사용하고 Single Node 아키텍처 적용
- [ ] AWX, Execution Environment, CloudStack Module 포함
- [ ] Genie VM 생성 자동화를 위한 절차 정리

**Comment by stardom3645** [comment]
- 서브 이슈 사항
  - genie 템플릿으로 genie VM 생성 후, 정상 작동을 위한 절차가 필요합니다.
    - [x] 포트포워딩(AWX 대시보드), 프록시(쿠버네티스 대시보드) 다시 시작
      - 프로세스가 종료되어도 프로세스 상태를 체크하여 재시작하는 서비스 개발(최초  vm부팅 시, minikube 시작 후 작동 되도록)
    - [x] awx 대시보드 admin 비밀번호가 초기화 되는 현상
      - 다른 관리자 User는 비밀번호가 초기화 되지 않아 별도 관리자 User 생성

**Comment by stardom3645** [comment]
- 추가해야할 Genie VM 설정

- [x] cloud-init 설치
$ dnf install -y cloud-init

- [x] sshd_config 파일에서 PasswordAuthentication yes 로 바꾸기
$ vi /etc/ssh/sshd_config
$ systemctl restart sshd

- [x] cloud-init user-data에 root 접근 허용해주기
$ mold에서 vm생성할 때 user-data에 disable_root: false
cloud.cfg
